name: Deploy to VPS

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala e Testa antes de enviar (Opcional, mas recomendado)
      # - name: Run Tests
      #   run: |
      #     npm ci
      #     npm run test

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Lógica de seleção de pasta baseada na Branch
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              DIR="/var/www/dashtechstore-prod"
              APP_NAME="dashtech-prod"
            else
              DIR="/var/www/dashtechstore-dev"
              APP_NAME="dashtech-dev"
            fi

            # Processo de Deploy
            echo "Deploying to $DIR..."
            
            # Se o diretório não existe, clona. Se existe, pull.
            if [ ! -d "$DIR/.git" ]; then
              git clone git@github.com:atomsdeveloper/app-web-app.git $DIR
              cd $DIR
            else
              cd $DIR
              git pull origin ${{ github.ref_name }}
            fi

            # Instalação e Build
            npm ci
            npx prisma generate
            npm run build
            
            # Restart PM2
            pm2 reload ecosystem.config.js --only $APP_NAME
